CREATE TABLE MEDICAL_PROCEDURE
(
    ID                  SERIAL PRIMARY KEY,
    CHAPTER_ID          VARCHAR,
    CHAPTER_TITLE       VARCHAR,
    SUB_CHAPTER_ID      VARCHAR,
    SUB_CHAPTER_TITLE   VARCHAR,
    MAIN_CATEGORY_ID    VARCHAR,
    MAIN_CATEGORY_TITLE VARCHAR,
    SUB_CATEGORY_ID     VARCHAR,
    SUB_CATEGORY_TITLE  VARCHAR
);
