CREATE TABLE VISIT
(
    ID                   SERIAL PRIMARY KEY,
    VISIT_DATE           DATE        NOT NULL,
    VISIT_TIME           TIME        NOT NULL,
    PAYMENT              VARCHAR(10) NOT NULL,
    STATUS               VARCHAR(10) NOT NULL,
    PATIENT_ID           INTEGER REFERENCES PATIENT (ID),
    MEDICAL_PROCEDURE_ID INTEGER REFERENCES MEDICAL_PROCEDURE (ID)
);

CREATE INDEX ON VISIT (PATIENT_ID);
CREATE INDEX ON VISIT (MEDICAL_PROCEDURE_ID);

