CREATE TABLE MEDICAL_PROCEDURE
(
    ID                  SERIAL PRIMARY KEY,
    CHAPTER_ID          VARCHAR NOT NULL,
    CHAPTER_TITLE       VARCHAR NOT NULL,
    SUB_CHAPTER_ID      VARCHAR NOT NULL,
    SUB_CHAPTER_TITLE   VARCHAR NOT NULL,
    MAIN_CATEGORY_ID    VARCHAR NOT NULL,
    MAIN_CATEGORY_TITLE VARCHAR NOT NULL,
    SUB_CATEGORY_ID     VARCHAR NOT NULL,
    SUB_CATEGORY_TITLE  VARCHAR NOT NULL
);
