INSERT INTO APPLICATION_USER (ID, USERNAME, PASSWORD, ROLE, STATUS)
VALUES (DEFAULT, 'admin', '$2a$12$ueZDdlkm.rWWG.qXSKqrfef8XVoKQWs09aT/36P3XG9TePrgyX812', 'ADMIN', 'ACTIVE'),
       (DEFAULT, 'receptionist', '$2a$12$ueZDdlkm.rWWG.qXSKqrfef8XVoKQWs09aT/36P3XG9TePrgyX812', 'RECEPTIONIST',
        'ACTIVE');